twig:
    form:
        resources:
            - 'PositibeOrmMediaBundle::_media_type.html.twig'

liip_imagine:
    filter_sets:
        # define the filter to be used with the image preview
        image_upload_thumbnail:
            filters:
                thumbnail: { size: [100, 100], mode: outbound }