#cmf_media_file:
#   resource: "@CmfMediaBundle/Resources/config/routing/file.xml"
#
#cmf_media_image:
#   resource: "@CmfMediaBundle/Resources/config/routing/image.xml"
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

_liip_imagine:
   resource: "@LiipImagineBundle/Resources/config/routing.xml"