positibe_media_image_display:
    path: /media/display/{path}
    defaults: { _controller: PositibeMediaBundle:File:display }
    requirements:
        method: GET
        path: .*

positibe_media_download:
    path: /media/download/{path}
    defaults: { _controller: PositibeMediaBundle:File:download }
    requirements:
        method: GET
        path: .*

positibe_media_upload:
    path: /media/image/upload/{editor}
    defaults: { _controller: PositibeMediaBundle:File:upload, editor: ckeditor, _format: json }
    requirements:
        method: POST

_liip_imagine:
   resource: "@LiipImagineBundle/Resources/config/routing.xml"