parameters:
    positibe_media.media_basepath: "/web/upload/image"
    positibe_media.filesystem_path: '%kernel.root_dir%/../web/'
    positibe_media.url_path: 'uploads/media'
    positibe_media.media.class: "Positibe\Bundle\MediaBundle\Entity\Media"

services:

#### Form Types ####

    positibe_media.form.gallery_type:
        class: Positibe\Bundle\MediaBundle\Form\Type\GalleryType
        tags:
            - {name: form.type }

    positibe_media.form.gallery_has_media_type:
        class: Positibe\Bundle\MediaBundle\Form\Type\GalleryHasMediaType
        tags:
            - {name: form.type}

    positibe_media.media_entity_listener:
        class: Positibe\Bundle\MediaBundle\EventListener\MediaEntityListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.orm.entity_listener }

    positibe_media.media_provider:
        class: Positibe\Bundle\MediaBundle\Provider\MediaProvider
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: positibe.media.provider }

    positibe_media.image_provider:
        class: Positibe\Bundle\MediaBundle\Provider\ImageProvider
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: positibe.media.provider }

    positibe_media.form.media_type:
        class: Positibe\Bundle\MediaBundle\Form\Type\MediaType
        arguments: ['%positibe_media.media.class%']
        tags:
            - { name: form.type }

    positibe_media.form.image_type:
        class: Positibe\Bundle\MediaBundle\Form\Type\ImageType
        arguments: ['%positibe_media.media.class%']
        tags:
            - { name: form.type }

    positibe_media.media_manager:
        class: Positibe\Bundle\MediaBundle\Media\MediaManager
        arguments: ['%positibe_media.filesystem_path%', "@doctrine.orm.entity_manager"]

    positibe_media.local_gaufrette_adapter:
        class: Gaufrette\Adapter\Local
        arguments: ['%positibe_media.filesystem_path%']

    positibe_media.filesystem:
        class: Gaufrette\Filesystem
        arguments: ['@positibe_media.local_gaufrette_adapter']

    positibe_media.upload_file_helper:
        class: Symfony\Cmf\Bundle\MediaBundle\File\UploadFileHelperDoctrine
        arguments: ['@doctrine', ~, '%positibe_media.media.class%', '/','@positibe_media.media_manager']

    positibe_media.twig.extension:
        class: Symfony\Cmf\Bundle\MediaBundle\Twig\Extension\CmfMediaExtension
        arguments: ['@positibe_media.templating.helper']
        tags:
            - { name: twig.extension }

    positibe_media.templating.helper:
        class: Symfony\Cmf\Bundle\MediaBundle\Templating\Helper\CmfMediaHelper
        arguments: ['@positibe_media.media_manager', '@router', '@liip_imagine.templating.helper']
        tags:
            - { name: templating.helper, alias: cmf_media }

    positibe_media.upload_editor_helper.ckeditor:
        class: Symfony\Cmf\Bundle\MediaBundle\Editor\Helper\UploadCkeditorHelper
        arguments: ['@positibe_media.media_manager', '@router']
        tags:
            - { name: cmf_media.upload_editor_helper, alias: ckeditor }