parameters:
    positibe_orm_media.media_basepath: /web/upload/image

services:

#### Form Types ####

    positibe_orm_media.form.galllery_form:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\GalleryType
        tags:
            - {name: form.type, alias: positibe_media_gallery }