parameters:
    positibe_media.media.class: 'Positibe\Bundle\MediaBundle\Entity\Media'
    positibe_media.media_basepath: "/web/upload/image"
    positibe_media.filesystem_path: '%kernel.root_dir%/../web/'
    positibe_media.url_path: 'uploads/media'

services:
    positibe_media.templating.helper:
        class: Positibe\Bundle\MediaBundle\Templating\Helper\MediaHelper
        arguments: ['@router', '@liip_imagine.templating.helper']
        tags:
            - { name: templating.helper, alias: positibe_media }

    positibe_media.twig.extension:
        class: Positibe\Bundle\MediaBundle\Twig\Extension\MediaExtension
        arguments: ['@positibe_media.templating.helper']
        tags:
            - { name: twig.extension }

    positibe_media.media_entity_listener:
        class: Positibe\Bundle\MediaBundle\EventListener\MediaEntityListener
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.orm.entity_listener }

    positibe_media.media_provider:
        class: Positibe\Bundle\MediaBundle\Provider\MediaProvider
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: positibe.media.provider }

    positibe_media.image_provider:
        class: Positibe\Bundle\MediaBundle\Provider\ImageProvider
        calls:
            - [ setContainer, ['@service_container']]
        tags:
            - { name: positibe.media.provider }

    positibe_media.form.media_type:
        class: Positibe\Bundle\MediaBundle\Form\Type\MediaType
        arguments: ['%positibe_media.media.class%']
        tags:
            - { name: form.type }

    positibe_media.form.image_type:
        class: Positibe\Bundle\MediaBundle\Form\Type\ImageType
        arguments: ['%positibe_media.media.class%']
        tags:
            - { name: form.type }

    positibe_media.media_manager:
        class: Positibe\Bundle\MediaBundle\Model\MediaManager
        arguments: ['%positibe_media.filesystem_path%', "@doctrine.orm.entity_manager"]

    positibe_media.local_gaufrette_adapter:
        class: Gaufrette\Adapter\Local
        arguments: ['%positibe_media.filesystem_path%']

    positibe_media.filesystem:
        class: Gaufrette\Filesystem
        arguments: ['@positibe_media.local_gaufrette_adapter']