parameters:
    positibe_media.media_class: 'Positibe\Bundle\MediaBundle\Entity\Media'
    positibe_media.url_path: 'uploads/media'
    positibe_media.web_root: "%kernel.root_dir%/../public/"
    positibe_media.cache_prefix: 'media/cache'
    positibe_media.upload_file_role: ROLE_EDITOR

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $mediaUrlPath: "%positibe_media.url_path%"
            $mediaClass: "%positibe_media.media_class%"
            $mediaFilesystemPath: "%positibe_media.web_root%"
            $mediaCachePath: "%positibe_media.cache_prefix%"


    Positibe\Bundle\MediaBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Positibe\Bundle\MediaBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Positibe\Bundle\MediaBundle\EventListener\MediaEntityListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    Gaufrette\Adapter\Local:
        arguments: ['%positibe_media.web_root%']

    Gaufrette\Filesystem:
        arguments: ['@Gaufrette\Adapter\Local']

    Liip\ImagineBundle\Templating\Helper\FilterHelper: "@liip_imagine.templating.filter_helper"
    Imagine\Image\ImagineInterface: "@liip_imagine"