parameters:
    positibe_orm_media.media_basepath: /web/upload/image
    positibe_orm_media.filesystem_path: '%kernel.root_dir%/../web/'
    positibe_orm_media.url_path: 'uploads/media'

services:

#### Form Types ####

    positibe_orm_media.form.gallery_type:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\GalleryType
        tags:
            - {name: form.type, alias: positibe_gallery_type }

    positibe_orm_media.form.gallery_has_media_type:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\GalleryHasMediaType
        tags:
            - {name: form.type, alias: positibe_gallery_has_media_type }

    positibe_orm_media.media_entity_listener:
        class: Positibe\Bundle\OrmMediaBundle\EventListener\MediaEntityListener
        arguments: [@service_container]

    positibe_orm_media.media_provider:
        class: Positibe\Bundle\OrmMediaBundle\Provider\MediaProvider
        calls:
            - [ setContainer, [@service_container]]
        tags:
            - { name: positibe.media.provider }

    positibe_orm_media.image_provider:
        class: Positibe\Bundle\OrmMediaBundle\Provider\ImageProvider
        calls:
            - [ setContainer, [@service_container]]
        tags:
            - { name: positibe.media.provider }

    positibe_orm_media.form.media_type:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\MediaType
        arguments: [%positibe_orm_media.media.class%]
        tags:
            - { name: form.type , alias: positibe_media_type }

    positibe_orm_media.form.image_type:
        class: Positibe\Bundle\OrmMediaBundle\Form\Type\ImageType
        arguments: [%positibe_orm_media.media.class%]
        tags:
            - { name: form.type , alias: positibe_image_type }

    positibe_orm_media.media_manager:
        class: Positibe\Bundle\OrmMediaBundle\Media\MediaManager
        arguments: [%positibe_orm_media.filesystem_path%]

    positibe_orm_media.local_gaufrette_adapter:
        class: Positibe\Bundle\OrmMediaBundle\Adapter\LocalGaufretteAdapter
        arguments: [%positibe_orm_media.filesystem_path%]

    positibe_orm_media.filesystem:
        class: Gaufrette\Filesystem
        arguments: [@positibe_orm_media.local_gaufrette_adapter]

    positibe_orm_media.upload_file_helper:
        class: Symfony\Cmf\Bundle\MediaBundle\File\UploadFileHelperDoctrine
        arguments: [@doctrine, ~, %positibe_orm_media.media.class%, '/', @positibe_orm_media.media_manager]

    positibe_orm_media.twig.extension:
        class: Symfony\Cmf\Bundle\MediaBundle\Twig\Extension\CmfMediaExtension
        arguments: [@positibe_orm_media.templating.helper]
        tags:
            - { name: twig.extension }

    positibe_orm_media.templating.helper:
        class: Symfony\Cmf\Bundle\MediaBundle\Templating\Helper\CmfMediaHelper
        arguments: [@positibe_orm_media.media_manager, @router, @liip_imagine.templating.helper]
        tags:
            - { name: templating.helper, alias: cmf_media }

    positibe_orm_media.upload_editor_helper.ckeditor:
        class: Symfony\Cmf\Bundle\MediaBundle\Editor\Helper\UploadCkeditorHelper
        arguments: [@positibe_orm_media.media_manager, @router]
        tags:
            - { name: cmf_media.upload_editor_helper, alias: ckeditor }